//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Klondike.rc
//
#define kStrAppTitle                    1
#define IDI_KLONDIKE_ICON               2
#define kStrUnsupportedVersion          2
#define kStrGamesPlayed                 3
#define kStrGamesWon                    4
#define kStrPercentWon                  5
#define kStrAverageCardsUp              6
#define kStrCardsUp                     7
#define kStrStrategy                    8
#define kStrCurrentOptions              9
#define kStrOneAtATime                  10
#define kStrThreeAtATime                11
#define kStrOneTime                     12
#define kStrThreeTimes                  13
#define kStrMultipleTime                14
#define kStrOPartialAllowed             15
#define kStrOPartialNotAllowed          16
#define kStrMoveWasteToFoundation       17
#define kStrMoveTableauToFoundation     18
#define kStrMoveWasteToTableau          19
#define kStrMoveTableauPile             20
#define kStrMovePartialTableauPile      21
#define kStrFlipTabeauFaceDownCard      22
#define kStrFlipDeckCards               23
#define kStrMoveWasteAceOrTwo           24
#define kStrMoveTableauAceOrTwo         25
#define kStrMoveTableauPileFromBigger   26
#define kStrMoveTableauPileFromSmaller  27
#define kStrMoveTableauToFoundationPlay 28
#define kStrMoveTableauPileMakingKingSpot 29
#define kStrMoveKingWhenJackIsAvailable 30
#define kStrMoveTableauPileUnlessEmpty  31
#define kStrFlipDeckWhenWastePileEmpty  32
#define kStrFlipWastePileMakingNewStock 33
#define kStrMoveTableauToFoundationOpeningFlip 34
#define kStrDeck                        35
#define kStrWastePile                   36
#define kStrFoundation                  37
#define kStrTableau                     38
#define kStrInvalidNameOrKey            39
#define kStrGoodNameAndKey              40
#define IDD_KLONDIKE_DIALOG             102
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDC_KLONDIKE_ACCELERATORS       106
#define IDC_KLONDIKE_MENU               107
#define IDM_VISITKEYPICT                108
#define IDR_MAINFRAME                   128
#define IDD_STRATEGY                    132
#define IDD_PLAYUNTIL                   133
#define IDD_OPTIONS                     134
#define IDD_NAMEANDKEY                  135
#define kSmallHeart                     150
#define kBigHeart                       151
#define kSmallDiamond                   152
#define kBigDiamond                     153
#define kSmallSpade                     154
#define kBigSpade                       155
#define kSmallClub                      156
#define kBigClub                        157
#define kKingHearts                     164
#define kKingSpades                     165
#define kKingDiamonds                   166
#define kKingClubs                      167
#define kQueenHearts                    168
#define kQueenSpades                    169
#define kQueenDiamonds                  170
#define kQueenClubs                     171
#define kJackHearts                     172
#define kJackSpades                     173
#define kJackDiamonds                   174
#define kJackClubs                      175
#define IDC_STRATEGYLIST                1000
#define IDC_STRATEGYLETTERS             1001
#define IDC_PLAYUNTILEDITBOX            1002
#define IDC_PLAYUNTILEDITBOX2           1003
#define IDC_PLAYUNTILCOMBOBOX           1004
#define IDC_PLAYUNTILGAMES              1005
#define IDC_PLAYUNTILCARDSUP            1006
#define IDC_PLAYUNTILWINMANY            1007
#define IDC_ONEATATIME                  1009
#define IDC_THREEATATIME                1010
#define IDC_ALLOWPARTIALPILEMOVES       1011
#define IDC_ANYCARD                     1012
#define kUserName                       1013
#define kKeyValue                       1014
#define kPictureControl                 1014
#define IDC_ONETIME                     1015
#define kPlayUntilPicture               1015
#define IDC_MULTIPLETIMES               1016
#define kStrategyPicture                1016
#define IDC_ABOUTPICTURE                1017
#define kNameAndKeyInstructions         1018
#define ID_FILE_DEAL                    32771
#define ID_FILE_PLAY                    32772
#define ID_FILE_MAKEMOVE                32773
#define ID_FILE_MOVE                    32774
#define ID_FILE_                        32778
#define ID_FILE_SHOWSTATISTICS          32779
#define ID_FILE_OPTIONS                 32780
#define ID_FILE_STRATEGY                32781
#define ID_FILE_EXIT                    32782
#define ID_FILE_SHOWMOVES               32784
#define ID_FILE_MOVE32785               32785
#define ID_FILE_PLAYUNTILWIN            32786
#define ID_FILE_REPLAYSAMEDECK          32787
#define ID_FILE_PLAYHAND                32788
#define ID_FILE_UNDO                    32791
#define ID_FILE_32794                   32794
#define ID_FILE_PLAYUNTIL               32795
#define ID_VIEW_BIGGER                  32796
#define ID_VIEW_SMALLER                 32797
#define ID_VIEW_DEFAULT                 32800
#define ID_VIEW_CLEARSTATISTICS         32801
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        136
#define _APS_NEXT_COMMAND_VALUE         32802
#define _APS_NEXT_CONTROL_VALUE         1017
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
